### ISSUE TITLE
Типізація

### ISSUE THREAD

**Issue by globerone** [KnackeredMe/renju#1]
https://github.com/KnackeredMe/renju/blame/311350eadcea06909aa0e0e62f459ea1332362c7/src/renju.ts#L21

Якщо ми ініціалізуємо число, то нам не потрібно повторно писати його тип. Тип вказуємо лише в тому випадку, якщо ми не інізіаліуємо змінну.

`let a = 1;`
`let a: number;`

**Comment by KnackeredMe** [comment]
Can't agree. Setting initial type makes code more readable. I personally prefer when type is set explicitly
